/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_slemenik_lidar_reconstruction_jni_JniLibraryHelpers */

#ifndef _Included_com_slemenik_lidar_reconstruction_jni_JniLibraryHelpers
#define _Included_com_slemenik_lidar_reconstruction_jni_JniLibraryHelpers
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_slemenik_lidar_reconstruction_jni_JniLibraryHelpers
	 * Method:    writeJNIPointList
	 * Signature: ([[D)V
	 */
	JNIEXPORT jint JNICALL Java_com_slemenik_lidar_reconstruction_jni_JniLibraryHelpers_writeJNIPointList
	(JNIEnv * env, jobject obj, jobjectArray pointsArray);

	/*
	 * Class:     com_slemenik_lidar_reconstruction_jni_JniLibraryHelpers
	 * Method:    writeJNIPoint
	 * Signature: (DDD)V
	 */
	JNIEXPORT void JNICALL Java_com_slemenik_lidar_reconstruction_jni_JniLibraryHelpers_writeJNIPoint
	(JNIEnv * env, jobject obj, jdouble x, jdouble y, jdouble z);

#ifdef __cplusplus
}
#endif
#endif
